### PR TITLE
feat(dashboardModals): Fixes create and edit dashboard modals, allowing ...

### LINKED ISSUE #424: Trying to edit a dashboard other than the current one fails
If you try to edit a dashboard other than the one you are currently on, it will open the modal to the current dashboard anyway.

### PR DESCRIPTION
**Pull request by hoganmaps**
...users to edit any dashboard or create new empty dashboards. Closes #424 #408 #428

### CODE REVIEW

File: src/app/models/dashboardApi.js [hunk 1]
```diff
@@ -532,9 +527,7 @@ function generalDashboardModel($sce, $q, $log, $http, $window, persistStrategy,
             frames[j].icon.small = marketplaceApps[i].icons.small;
             frames[j].icon.large = marketplaceApps[i].icons.large;
             frames[j].url = marketplaceApps[i].launchUrls.default;
-            var utils = new Utilities();
-            var newUrl = utils.updateQueryString('ozpIwc.peer', iwcConnectedClient.getIwcBusUrl(), frames[j].url);
-            frames[j].trustedUrl = $sce.trustAsResourceUrl(newUrl);
+            frames[j].trustedUrl = $sce.trustAsResourceUrl(frames[j].url + '?ozpIwc.peer=' + iwcConnectedClient.getIwcBusUrl());
```
Comment (arw180) [inline src/app/models/dashboardApi.js]: Aaah!! Why was this previous fix undone in this merge?!

File: src/app/models/dashboardApi.spec.js [hunk 2]
```diff
@@ -394,45 +394,45 @@ describe('Service: dashboardApi', function () {
     if(!rootScope.$$phase) { rootScope.$apply(); }
   });
 
-  // update the current dashboard
-  it('should have a updateCurrentDashboardName method - return false on invalid dashboard name', function(done) {
```
Comment (arw180) [inline src/app/models/dashboardApi.spec.js]: If you need to remove a test for some reason, use `xit` instead of commenting it out. That way, we can see in the test report how many (and which) tests were skipped, making it more probable that they will eventually get fixed

File: src/app/models/dashboardApi.js [hunk 3]
```diff
@@ -465,36 +465,31 @@ function generalDashboardModel($sce, $q, $log, $http, $window, persistStrategy,
...
       return this.getDashboardData().then(function(dashboardData) {
-        var dashboardFound = false;
         for (var i=0; i < dashboardData.dashboards.length; i++) {
-          if (dashboardData.dashboards[i].name === dashboardName) {
-            dashboardData.currentDashboard = dashboardData.dashboards[i].id;
-            dashboardFound = true;
+          if(dashboardData.dashboards[i].id === updatedDashboardData.id) {
+            dashboardData.dashboards[i].name = updatedDashboardData.name;
+            dashboardData.dashboards[i].layout = updatedDashboardData.layout;            
+            that._setDashboardData(dashboardData).then(function(response) {
```
Comment (arw180) [inline src/app/models/dashboardApi.js]: missing a return on this promise - pretty sure this would not pass a unit test if there was one
